# Generated by Django 3.1.7 on 2021-03-27 17:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_text', models.CharField(max_length=200)),
                ('data_registro', models.DateTimeField(verbose_name='data de registro')),
            ],
        ),
        migrations.CreateModel(
            name='Atuacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atuacao_text', models.CharField(max_length=200)),
                ('minutos', models.IntegerField(default=0)),
                ('data_historico', models.DateTimeField(verbose_name='date published')),
                ('registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exemplo.registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
